### ISSUE TITLE
Complexity feedback

### ISSUE THREAD

**Issue by fletchgqc** [dennisschroeder/thoughts-on#1]
1. The basic point, that complexity is a massive problem, makes sense to me.
2. The industry examples are interesting
3. Fred Brooks is mostly known for The Mythical Man Month.
4. Swap the order of accidental and essential complexity.
5. Ironically, "Hexagonal Architecture" also adds complexity. I have found that good software teams sometimes remove parts of it, particularly the interfaces and splitting into modules, to reduce cost of change. So, yeah, there is some value and some YAGNI in these architectural solutions, in my opinion.
6. Of course I like the bit about "Maximise the amount of work not done" and "Lean Experimentation" the most :). The tricky thing is how to get people to actually do this stuff. I'm still working on that. I came up with the name "push towards production" the other day for what I try to to. Last week I started a project which wants to first deliver value to users after 1 year. I want to influence (push) them to offer some small part of the system to the users much sooner.
7. I like the conclusion. This sums up the message pretty well.

All in all it makes sense, the hard part is in influencing people around you to understand the danger their product is in, and to change their thinking. That's why I tell people that I work as a psychologist :). Let me know if you have any tips for this.

**Comment by dennisschroeder** [comment]
3. Changed that ... thx
4. Why do you think it is beneficial to switch the two bits?
5. The main point was not that I wanted to propose a particular architectural style but rather what we achieve with it in the example I presented. If there are other ways to get to this, that's okay. I think it is worth the extra effort and procedural complexity if the code you have to structure has a high frequency of change and therefore the cost of change needs to be low. 
6. I think the hard part is always the people working together. There is a lot of complexity in it. You never really know how people react to change ;-) 

```
All in all it makes sense, the hard part is in influencing people around you to understand the danger their product is in and to change their thinking. That's why I tell people that I work as a psychologist :). Let me know if you have any tips for this.
```

Haven't figured that part out yet either. But I had at least resistance when saying ... I have this Idea, can we try this as an experiment. I guess the indication of seeing it only as an experiment gives the Team some safety that the change is not forever or that there is a chance of not doing it when the experiment fails.

Anyways, thanks a lot for the feedback. Really appreciate your time and thoughts.

**Comment by fletchgqc** [comment]
4. I just think it makes more logical sense to have the shorter one out of the way first, but it doesn't matter.

Yeah the experiment thing is good. Setting a review date makes it even better: e.g. "in 1 month we'll discuss whether we like it."

**Comment by dennisschroeder** [comment]
Setting up a `review date` right from the start is a good idea.
